package repita;

import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import componentes.TextLineNumber;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIDefaults;

/**
 *
 * @author Hugo Carvalho
 */
public class Editor extends javax.swing.JPanel {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        
        /*AbstractDocument document = (AbstractDocument) jTextAreaScript.getDocument();
        CustomDocumentFilter customDocumentFilter = new CustomDocumentFilter(jTextAreaScript);
        document.setDocumentFilter(customDocumentFilter);*/

        TextLineNumber contadorLinhas = new TextLineNumber(jTextAreaScript);

        jScrollPane.setRowHeaderView(contadorLinhas);

        Color backgroundColor = new Color(40, 41, 35);
        UIDefaults defaults = new UIDefaults();
        defaults.put("TextPane[Enabled].backgroundPainter", backgroundColor);
        jTextAreaScript.putClientProperty("Nimbus.Overrides", defaults);
        jTextAreaScript.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
        jTextAreaScript.setBackground(backgroundColor);

        jTextAreaScript.setBorder(BorderFactory.createEmptyBorder());

        jTextAreaScript.setBorder(BorderFactory.createLineBorder(backgroundColor, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaScript = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(40, 41, 35));

        jScrollPane.setBackground(new java.awt.Color(40, 41, 35));

        jTextAreaScript.setBackground(new java.awt.Color(40, 41, 35));
        jTextAreaScript.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jTextAreaScript.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaScript.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaScriptKeyPressed(evt);
            }
        });
        jScrollPane.setViewportView(jTextAreaScript);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaScriptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaScriptKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaScriptKeyPressed

    public JScrollPane getjScrollPane() {
        return jScrollPane;
    }

    public JTextPane getjTextAreaScript() {
        return jTextAreaScript;
    }

    public File getArquivo() {
        return arquivo;
    }

    public void setArquivo(File arquivo) {
        this.arquivo = arquivo;
    }

    public boolean isSalvo() {
        return salvo;
    }

    public void setSalvo(boolean salvo) {
        this.salvo = salvo;
    }

    public boolean isClassInserido() {
        return classInserido;
    }

    public void setClassInserido(boolean classInserido) {
        this.classInserido = classInserido;
    }

    private File arquivo;
    private boolean salvo, classInserido;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextPane jTextAreaScript;
    // End of variables declaration//GEN-END:variables
}
