/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repita;

import com.sun.awt.AWTUtilities;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.lang.reflect.Field;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author hugan
 */
public class Localizar extends javax.swing.JFrame {

    /**
     * Creates new form Localizar
     * @throws java.lang.NoSuchFieldException
     * @throws java.lang.IllegalAccessException
     */
    private Localizar() {
        initComponents();
        try {
            undecored(this);
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
            Logger.getLogger(Localizar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLocalizar = new javax.swing.JButton();
        jTextFieldLocalizar = new javax.swing.JTextField();
        jLabelLocalizar = new javax.swing.JLabel();
        jLabelSubstituir = new javax.swing.JLabel();
        jTextFieldSubstituir = new javax.swing.JTextField();
        jButtonSubstituir = new javax.swing.JButton();
        jButtonSubstituirTodos = new javax.swing.JButton();
        jButtonLocalizarProxima = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLocalizarMouseEntered(evt);
            }
        });

        jTextFieldLocalizar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextFieldLocalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldLocalizarMouseEntered(evt);
            }
        });
        jTextFieldLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLocalizarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLocalizarKeyReleased(evt);
            }
        });

        jLabelLocalizar.setText("Localizar:");
        jLabelLocalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLocalizarMouseEntered(evt);
            }
        });

        jLabelSubstituir.setText("Substituir por:");
        jLabelSubstituir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSubstituirMouseEntered(evt);
            }
        });

        jTextFieldSubstituir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextFieldSubstituir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSubstituirMouseEntered(evt);
            }
        });
        jTextFieldSubstituir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSubstituirKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSubstituirKeyReleased(evt);
            }
        });

        jButtonSubstituir.setText("Substituir");
        jButtonSubstituir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSubstituirMouseEntered(evt);
            }
        });

        jButtonSubstituirTodos.setText("Substituir todos");
        jButtonSubstituirTodos.setToolTipText("");
        jButtonSubstituirTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSubstituirTodosMouseEntered(evt);
            }
        });

        jButtonLocalizarProxima.setText("Localizar proxima");
        jButtonLocalizarProxima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLocalizarProximaMouseEntered(evt);
            }
        });

        jCheckBox1.setText("Diferenciar maiúsculas/minúsculas");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSubstituir)
                            .addComponent(jLabelLocalizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSubstituir, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jTextFieldLocalizar)))
                    .addComponent(jCheckBox1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSubstituirTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSubstituir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLocalizarProxima, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jButtonLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLocalizar)
                    .addComponent(jTextFieldLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSubstituir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubstituir)
                    .addComponent(jButtonLocalizarProxima))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubstituir)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSubstituirTodos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLocalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalizarKeyPressed
        localizarStr = jTextFieldLocalizar.getText();
    }//GEN-LAST:event_jTextFieldLocalizarKeyPressed

    private void jTextFieldLocalizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalizarKeyReleased
        localizarStr = jTextFieldLocalizar.getText();
    }//GEN-LAST:event_jTextFieldLocalizarKeyReleased

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        AWTUtilities.setWindowOpacity(this, 0.5f);
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_formMouseEntered

    private void jTextFieldLocalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLocalizarMouseEntered
       AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jTextFieldLocalizarMouseEntered

    private void jTextFieldSubstituirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSubstituirMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jTextFieldSubstituirMouseEntered

    private void jLabelLocalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLocalizarMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jLabelLocalizarMouseEntered

    private void jLabelSubstituirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubstituirMouseEntered
       AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jLabelSubstituirMouseEntered

    private void jButtonLocalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLocalizarMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jButtonLocalizarMouseEntered

    private void jButtonSubstituirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubstituirMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jButtonSubstituirMouseEntered

    private void jButtonSubstituirTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubstituirTodosMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jButtonSubstituirTodosMouseEntered

    private void jButtonLocalizarProximaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLocalizarProximaMouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jButtonLocalizarProximaMouseEntered

    private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
        AWTUtilities.setWindowOpacity(this, 1.0f);
    }//GEN-LAST:event_jCheckBox1MouseEntered

    private void jTextFieldSubstituirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubstituirKeyPressed
        substituirStr = jTextFieldSubstituir.getText();
    }//GEN-LAST:event_jTextFieldSubstituirKeyPressed

    private void jTextFieldSubstituirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubstituirKeyReleased
        substituirStr = jTextFieldSubstituir.getText();
    }//GEN-LAST:event_jTextFieldSubstituirKeyReleased

    private void undecored(JFrame jFrame) throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException{
        Field undecoratedField = Frame.class.getDeclaredField("undecorated");
        undecoratedField.setAccessible(true);
        undecoratedField.set(jFrame, true);
    }
    
    public void addActionListenerjButtonLocalizar(ActionListener listener) {
        jButtonLocalizar.addActionListener(listener);
    }
    
    public void addActionListenerjButtonLocalizarProxima(ActionListener listener) {
        jButtonLocalizarProxima.addActionListener(listener);
    }
    
    public void addActionListenerjButtonSubstituir(ActionListener listener) {
        jButtonSubstituir.addActionListener(listener);
    }

    public String getLocalizarStr() {
        return localizarStr;
    }

    public String getSubstituirStr() {
        return substituirStr;
    }
    
    public static synchronized Localizar getInstancia() {
        if(instancia == null){
            instancia = new Localizar();
        } else {
            instancia.requestFocus();
        }
        return instancia;
    }
    
    
    private static Localizar instancia;
    private String localizarStr;
    private String substituirStr;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonLocalizarProxima;
    private javax.swing.JButton jButtonSubstituir;
    private javax.swing.JButton jButtonSubstituirTodos;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabelLocalizar;
    private javax.swing.JLabel jLabelSubstituir;
    private javax.swing.JTextField jTextFieldLocalizar;
    private javax.swing.JTextField jTextFieldSubstituir;
    // End of variables declaration//GEN-END:variables
}
